services:
  libraries:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src/test/resources/libraries:/usr/share/nginx/html:ro
      - ./nginx_lib_dev.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  ai:
    image: leto-modelizer-ai-proxy:latest
    ports:
      - "8585:8585"
    network_mode: "host"
    restart: always
  db:
    image: cockroachdb/cockroach:v23.1.15
    command: start-single-node --certs-dir=/certs --advertise-addr=db
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./cockroach-certs:/certs
    ports:
      - "26257:26257"
      - "8081:8080"
    restart: always
  api:
    restart: always
    image: leto-modelizer-api:latest
    environment:
      DATABASE_HOST: db:26257
      AI_HOST: http://ai/
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      LIBRARY_HOST_WHITELIST: http://libraries/
      SUPER_ADMINISTRATOR_LOGIN: ${SUPER_ADMINISTRATOR_LOGIN}
      AI_SECRETS_ENCRYPTION_KEY: ${AI_SECRETS_ENCRYPTION_KEY}
    ports:
      - "8443:8443"
    depends_on:
      - db
