services:
  libraries:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src/test/resources/libraries:/usr/share/nginx/html:ro
      - ./nginx_lib_dev.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  ai:
    build: ./src/test/resources/ai
    ports:
      - "8585:80"
    volumes:
      - ./src/test/resources/ai:/var/www/html
    restart: always
  db:
    image: cockroachdb/cockroach:v23.1.15
    command: start-single-node --certs-dir=/certs --advertise-addr=db
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./cockroach-certs:/certs
    ports:
      - "26257:26257"
      - "8081:8080"
    restart: always
  api:
    restart: always
    image: leto-modelizer-api:latest
    environment:
      DATABASE_HOST: db:26257
      AI_HOST: http://ai/
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      LIBRARY_HOST_WHITELIST: http://libraries/
      SUPER_ADMINISTRATOR_LOGIN: ${SUPER_ADMINISTRATOR_LOGIN}
      POSTGRES_DB: ${POSTGRES_DB:-leto_db}
      POSTGRES_USER: ${POSTGRES_USER:-leto_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-leto_db}
      DATABASE_USER: ${DATABASE_USER:-leto_admin}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      SSL_KEY_STORE: ${SSL_KEY_STORE:-classpath:keystore.jks}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD:-password}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD:-password}
      LETO_MODELIZER_URL: ${LETO_MODELIZER_URL:-http://localhost:8080/}
      LETO_ADMIN_URL: ${LETO_ADMIN_URL:-http://localhost:9000/}
      CSRF_TOKEN_TIMEOUT: ${CSRF_TOKEN_TIMEOUT:-3600}
      USER_SESSION_TIMEOUT: ${USER_SESSION_TIMEOUT:-3600}
      AI_SECRETS_ENCRYPTION_KEY: the most secure key for secrets

    ports:
      - "8443:8443"
    depends_on:
      - db
