version: '3'

services:
  libraries:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src/test/resources/libraries:/usr/share/nginx/html:ro
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: leto_db
      POSTGRES_USER: leto_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    restart: always
    image: leto-modelizer-api:latest
    environment:
      DATABASE_HOST: db
      LIBRARY_HOST_WHITELIST: http://localhost/
    ports:
      - "8443:8443"
    depends_on:
      - db
