name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  delete-comments:
    name: Delete bot comment(s)
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

  branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9_.-]+$'
          allowed_prefixes: 'feature,bugfix,improvement,library,prerelease,release,hotfix'
          ignore: main
          min_length: 5
          max_length: 50

  checkstyle:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute checkstyle
        run: ./gradlew checkstyleMain

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Generate certificate
        run: |
          keytool \
          -genkeypair -v \
          -alias mykey \
          -dname "CN=Test, OU=Test, O=Test, L=Test, S=Test, C=Test" \
          -keystore src/main/resources/keystore.jks \
          -storepass password \
          -keypass password \
          -keyalg RSA \
          -keysize 2048 \
          -validity 3650
      - name: Build application
        run: docker build -t leto-modelizer-api .
      - name: Run application
        run: docker compose up -d
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute tests
        run: ./gradlew test
      - name: Upload line coverage report
        uses: actions/upload-artifact@v3
        with:
          name: reports-${{ github.sha }}
          path: build/reports/jacoco/test/jacocoTestReport.xml

  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute check dependencies
        run: ./gradlew dependencyUpdates
      - name: Post comment
        uses: luukkemp/pr-comment@2024.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: build/dependencyUpdates/report.txt

  sonarcloud:
    name: SonarCloud
    needs: [checkstyle, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Download line coverage report
        uses: actions/download-artifact@v3
        with:
          name: reports-${{ github.sha }}
          path: build/reports/jacoco/test/jacocoTestReport.xml
      - name: Execute sonar scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dsonar.token=$SONAR_TOKEN
